import Config

hexdocs_data_path = Path.expand("~/.hexdocs_mcp")

config :hexdocs_mcp,
  data_path: hexdocs_data_path,
  default_embedding_model: "nomic-embed-text",
  project_paths:
    System.get_env(
      "HEXDOCS_MCP_MIX_PROJECT_PATHS",
      "/Users/urielmaldonado/projects/eits/web/mix.exs"
    ),
  system_command: "mix hex.docs.mcp"

config :hexdocs_mcp, HexdocsMcp.Repo, database: Path.join(hexdocs_data_path, "hexdocs_mcp.db")

config :eye_in_the_sky, :env, :dev
# Core-layer config keys — keeps core modules free of EyeInTheSkyWeb.Endpoint atom references
config :eye_in_the_sky,
  secret_key_base: "N/iElaaIGg/5yCN4JOKd13aAXziMbsBDWfTjQFgjjLY32KpeZ7hBDnQEx1AcpSLO",
  server_base_url: "http://localhost:#{System.get_env("PORT", "5001")}"

config :eye_in_the_sky, :bypass_auth, System.get_env("BYPASS_AUTH", "true") in ~w(true 1)
config :eye_in_the_sky, digest_desktop_path: Path.expand("~/Desktop")

# Configure your database
config :eye_in_the_sky, EyeInTheSky.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "eits_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  log: false,
  prepare: :unnamed

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :eye_in_the_sky, EyeInTheSkyWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [port: String.to_integer(System.get_env("PORT", "5001"))],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "N/iElaaIGg/5yCN4JOKd13aAXziMbsBDWfTjQFgjjLY32KpeZ7hBDnQEx1AcpSLO",
  watchers:
    (if System.get_env("SKIP_WATCHERS") in ["1", "true"] do
       []
     else
       [
         vite: {PhoenixVite.Npm, :run, [:vite, ~w(dev)]},
         tailwind: {Tailwind, :install_and_run, [:eye_in_the_sky, ~w(--watch)]}
       ]
     end)

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :eye_in_the_sky, EyeInTheSkyWeb.Endpoint,
  live_reload:
    (if System.get_env("LIVE_RELOAD") in ["0", "false"] do
       []
     else
       [
         web_console_logger: true,
         patterns: [
           ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
           ~r"priv/gettext/.*(po)$",
           ~r"lib/eye_in_the_sky/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
         ]
       ]
     end)

# LiveSvelte SSR via Vite dev server in development
config :live_svelte,
  ssr_module: LiveSvelte.SSR.ViteJS,
  vite_host: "http://127.0.0.1:#{System.get_env("VITE_PORT", "5173")}"

config :eye_in_the_sky, :vite_host, "http://127.0.0.1:#{System.get_env("VITE_PORT", "5173")}"

# Enable dev routes for dashboard and mailbox
config :eye_in_the_sky, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
