import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :eye_in_the_sky, EyeInTheSkyWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# All LiveSvelte components use ssr={false} — no Node.js runtime required.
# Using ViteJS module skips NodeJS.Supervisor entirely, which would otherwise
# fail to start when launched from Finder/Alfred (minimal PATH, no node binary).
config :live_svelte, ssr_module: LiveSvelte.SSR.ViteJS

# Configures Swoosh API Client
config :swoosh, api_client: false

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
