defmodule EyeInTheSkyWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :eye_in_the_sky
  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  # PHX_INSECURE_COOKIES=1 at compile time bakes `secure: false` into the
  # session cookie. Needed for the Tauri bundle which loads http://localhost:5050
  # in a WebView — WebKit discards `secure` cookies over plain HTTP, causing a
  # LiveView mount loop as the session never persists across requests.
  @secure_cookies System.get_env("PHX_INSECURE_COOKIES") != "1" and
                    Application.compile_env(:eye_in_the_sky, :env) != :dev

  @session_options [
    store: :cookie,
    key: "_eye_in_the_sky_key",
    signing_salt: "Zx+j4lGh",
    same_site: "Lax",
    http_only: true,
    secure: @secure_cookies
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :eye_in_the_sky,
    gzip: not code_reloading?,
    only: EyeInTheSkyWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :eye_in_the_sky
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    body_reader: {EyeInTheSkyWeb.Plugs.CaptureRawBody, :read_body, []},
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  # Rewrite conn.remote_ip from X-Forwarded-For when behind ngrok/Tailscale/reverse proxy.
  # 100.64.0.0/10 is Tailscale's CGNAT range — trust XFF from those peers.
  # For ngrok the tunnel agent runs on localhost so 127.0.0.1 is already in RemoteIp's
  # reserved set; ngrok controls the XFF header so spoofing isn't possible through it.
  plug RemoteIp, proxies: ~w[100.64.0.0/10]
  plug Plug.Session, @session_options
  plug EyeInTheSkyWeb.Router
end
